// --- ADMIN -------------------------------------------------------------------
export const ADMIN_USER = "nexusadmin";
export const ADMIN_PASS = "N3xus@2025";

// -- AI Configuration ----------------------------------------------------------
export const OPENROUTER_KEY = "PASTE_YOUR_OPENROUTER_KEY_HERE";
export const AI_MODEL = "google/gemma-3-27b-it:free";

// --- SLUG HELPER --------------------------------------------------------------
export const slugify = str =>
  str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').slice(0, 80);

// --- TOPICS ------------------------------------------------------------------
export const TOPICS = [
  "All Topics",
  "Government & Intelligence",
  "Unresolved Events",
  "Hidden History",
  "Health & Science",
  "Finance & Power",
  "UAP & Anomalous",
  "Ocean & Earth",
  "Media & Disclosure",
  "Surveillance",
  "Ancient Civilizations",
  "Giants & Nephilim",
  "Biblical & Religious Records",
  "Animal Intelligence",
  "Forbidden Science",
  "Lost Technology",
  "Secret Societies",
  "Geopolitics & Deep State",
  "Vaccines & Big Pharma",
  "Food & Biotech",
  "Ticks & Bioweapons",
  "DNA & Genetics",
  "Frequency & Energy",
  "Consciousness & Mind",
  "Simulation & Reality",
  "Ancient Gods & Beings",
  "Sacred Geometry",
  "Atlantis & Lemuria",
  "Remote Viewing & PSI",
  "Portals & Stargates",
];

export const REGIONS = [
  "All Regions","USA","UK","Global","Russia",
  "China","Egypt","Asia Pacific","Europe",
  "South America","Middle East","Africa","Vatican",
];

export const VERDICTS = {
  confirmed:  { label:"Confirmed Record", short:"CONFIRMED",  color:"#0d2010", text:"#40c070", border:"#1a4a1a", icon:"+" },
  likely:     { label:"Likely Accurate",  short:"LIKELY",     color:"#0d1e10", text:"#60d080", border:"#1a3a1a", icon:"^" },
  contested:  { label:"Disputed",         short:"DISPUTED",   color:"#1e1a08", text:"#c0a020", border:"#3a3010", icon:"" },
  unverified: { label:"Unverified",       short:"UNVERIFIED", color:"#1a1008", text:"#c07820", border:"#3a2810", icon:"?" },
  refuted:    { label:"Refuted",          short:"REFUTED",    color:"#1a0808", text:"#c04040", border:"#3a1010", icon:"x" },
};

export const autoVerdict = c =>
  c >= 88 ? "confirmed" : c >= 72 ? "likely" : c >= 50 ? "contested" : c >= 30 ? "unverified" : "refuted";

export const TYPE_COLORS = {
  news:    { bg:"#0d1a2a", text:"#5a9ac8", label:"NEWS" },
  blog:    { bg:"#0d1a10", text:"#4a9a5a", label:"BLOG" },
  archive: { bg:"#1e1408", text:"#c08030", label:"ARCHIVE" },
  research:{ bg:"#140d1a", text:"#8a5ac8", label:"RESEARCH" },
  podcast: { bg:"#0d1a1a", text:"#4ab8b0", label:"PODCAST" },
  user:    { bg:"#141414", text:"#9a9a9a", label:"COMMUNITY" },
  reddit:  { bg:"#1a0a04", text:"#e06030", label:"REDDIT" },
};

export const fmtNum = n => n >= 1000 ? (n / 1000).toFixed(1) + "k" : String(n);
export const getType = t => TYPE_COLORS[t] || TYPE_COLORS.user;

// --- REDDIT SUBREDDITS --------------------------------------------------------
export const REDDIT_SUBS = [
  {name:"r/conspiracy",           url:"https://www.reddit.com/r/conspiracy",           color:"#ff6314", desc:"1.9M  -  alternative viewpoints"},
  {name:"r/UFOs",                 url:"https://www.reddit.com/r/UFOs",                 color:"#4488ff", desc:"UAP & disclosure"},
  {name:"r/HighStrangeness",      url:"https://www.reddit.com/r/HighStrangeness",      color:"#9944cc", desc:"Paranormal & unexplained"},
  {name:"r/conspiracytheories",   url:"https://www.reddit.com/r/conspiracytheories",   color:"#e04444", desc:"Theory & debate"},
  {name:"r/Paranormal",           url:"https://www.reddit.com/r/Paranormal",           color:"#6644aa", desc:"Supernatural events"},
  {name:"r/UnresolvedMysteries",  url:"https://www.reddit.com/r/UnresolvedMysteries",  color:"#44aaff", desc:"Cold cases & strange events"},
  {name:"r/AlternativeHistory",   url:"https://www.reddit.com/r/AlternativeHistory",   color:"#88aa44", desc:"Suppressed history"},
  {name:"r/AncientAliens",        url:"https://www.reddit.com/r/AncientAliens",        color:"#20c8a0", desc:"Ancient astronaut theory"},
  {name:"r/GrahamHancock",        url:"https://www.reddit.com/r/GrahamHancock",        color:"#a0c820", desc:"Lost civilization research"},
  {name:"r/SimulationTheory",     url:"https://www.reddit.com/r/SimulationTheory",     color:"#20a0c8", desc:"Are we in a simulation?"},
  {name:"r/MandelaEffect",        url:"https://www.reddit.com/r/MandelaEffect",        color:"#c820a0", desc:"Collective memory anomalies"},
  {name:"r/Missing411",           url:"https://www.reddit.com/r/Missing411",           color:"#c82020", desc:"David Paulides missing persons"},
  {name:"r/Giants",               url:"https://www.reddit.com/r/Giants",               color:"#aa6622", desc:"Giants & Nephilim"},
  {name:"r/Glitch_in_the_Matrix", url:"https://www.reddit.com/r/Glitch_in_the_Matrix", color:"#20c840", desc:"Reality glitches & anomalies"},
  {name:"r/Bigfoot",              url:"https://www.reddit.com/r/Bigfoot",              color:"#6a4020", desc:"Bigfoot & cryptid research"},
  {name:"r/UAP",                  url:"https://www.reddit.com/r/UAP",                  color:"#2080c8", desc:"UAP evidence"},
  {name:"r/InterdimensionalNHI",  url:"https://www.reddit.com/r/InterdimensionalNHI",  color:"#8020c8", desc:"Non-human intelligence"},
  {name:"r/RemoteViewing",        url:"https://www.reddit.com/r/RemoteViewing",        color:"#c8a020", desc:"Remote viewing research"},
  {name:"r/Area51",               url:"https://www.reddit.com/r/Area51",               color:"#208020", desc:"Area 51 & secret bases"},
  {name:"r/MKUltra",              url:"https://www.reddit.com/r/MKUltra",              color:"#c04040", desc:"CIA mind control programs"},
  {name:"r/Epstein",              url:"https://www.reddit.com/r/Epstein",              color:"#a04000", desc:"Epstein network research"},
  {name:"r/OccultConspiracy",     url:"https://www.reddit.com/r/OccultConspiracy",     color:"#404080", desc:"Occult & hidden power"},
  {name:"r/ForbiddenKnowledge",   url:"https://www.reddit.com/r/ForbiddenKnowledge",   color:"#802040", desc:"Suppressed knowledge"},
  {name:"r/SkinWalkerRanch",      url:"https://www.reddit.com/r/SkinWalkerRanch",      color:"#20c880", desc:"Paranormal ranch research"},
];

// --- SEED STORIES -------------------------------------------------------------
export const SEED_STORIES = [
  { id:"s1",  slug:"operation-northwoods-joint-chiefs-proposed-staging-domestic-attacks-to-justify-w", type:"archive",  source:"National Security Archive", sourceUrl:"https://nsarchive.gwu.edu",         time:"1h ago",  topic:"Government & Intelligence",    region:"USA",title:"Operation Northwoods: Joint Chiefs Proposed Staging Domestic Attacks to Justify War",                     summary:"The 1962 document proposed faking attacks on American soil to justify invading Cuba. JFK rejected it. Declassified in 1997  -  a primary example of documented false-flag planning within the U.S. military establishment.",                                     upvotes:4100, comments:529,  credible:94, debunked:6,  tags:["Declassified","False Flag","Military"],           premium:false },
  { id:"s2",  slug:"book-of-enoch-the-watchers-who-took-human-wives-and-produced-the-nephilim-comple", type:"archive",  source:"Dead Sea Scrolls Archive",  sourceUrl:"https://www.deadseascrolls.org.il", time:"2h ago",  topic:"Biblical & Religious Records",  region:"Middle East",title:"Book of Enoch: The Watchers Who Took Human Wives and Produced the Nephilim  -  Complete Pre-Biblical Account", summary:"The Book of Enoch, found among the Dead Sea Scrolls, describes the Watchers  -  fallen angels  -  who descended to earth, took human wives, and produced the Nephilim giants. The text directly influenced Genesis 6 and was excluded from the Biblical canon at the Council of Nicaea.", upvotes:6821, comments:1102, credible:78, debunked:22, tags:["Enoch","Watchers","Nephilim","Giants"],          premium:false },
  { id:"s3",  slug:"19th-century-newspaper-reports-of-giant-skeletal-remains-across-north-america-ca", type:"research", source:"Smithsonian Archives Review",sourceUrl:"https://www.si.edu",               time:"3h ago",  topic:"Giants & Nephilim",            region:"USA",title:"19th Century Newspaper Reports of Giant Skeletal Remains Across North America  -  Catalogued",               summary:"Over 400 newspaper articles from 1848-1912 report giant humanoid skeletons  -  some 7 to 12 feet tall  -  across the American Midwest. Researchers allege the Smithsonian systematically collected and suppressed these remains following its founding mandate.",      upvotes:9100, comments:1841, credible:65, debunked:35, tags:["Giants","Nephilim","Smithsonian","Cover-up"],    premium:false },
  { id:"s4",  slug:"dolphin-communication-evidence-of-names-syntax-and-cultural-transmission-across-", type:"research", source:"Marine Biology Quarterly",   sourceUrl:"https://www.tos.org",              time:"4h ago",  topic:"Animal Intelligence",           region:"Global",title:"Dolphin Communication: Evidence of Names, Syntax, and Cultural Transmission Across Generations",           summary:"Peer-reviewed research documents dolphins using unique signature whistles as individual names, teaching tool use across generations, and displaying syntax in communication  -  cognitive capabilities that challenge assumptions about uniquely human language.",     upvotes:4211, comments:621,  credible:88, debunked:12, tags:["Dolphins","Intelligence","Language"],            premium:false },
  { id:"s5",  slug:"mk-ultra-cia-mind-control-experiments-on-unwitting-citizens-confirmed-by-senate-1", type:"archive",  source:"CIA Reading Room",           sourceUrl:"https://www.cia.gov/readingroom",  time:"5h ago",  topic:"Government & Intelligence",    region:"USA",title:"MK-Ultra: CIA Mind Control Experiments on Unwitting Citizens  -  Confirmed by Senate 1977",                  summary:"The CIA ran LSD, hypnosis, and electroshock experiments on unwitting subjects for two decades. Confirmed by the Church Committee. Files were partially destroyed before the 1977 disclosure.",                                                              upvotes:7200, comments:1102, credible:96, debunked:4,  tags:["MK-Ultra","CIA","Declassified"],                  premium:false },
  { id:"s6",  slug:"nsa-metadata-collection-exceeded-legal-mandate-internal-analysts-raised-concerns", type:"news",     source:"The Intercept",              sourceUrl:"https://theintercept.com",         time:"6h ago",  topic:"Surveillance",                 region:"USA",title:"NSA Metadata Collection Exceeded Legal Mandate  -  Internal Analysts Raised Concerns",                     summary:"FOIA documents show NSA analysts raised concerns that domestic metadata collection exceeded FISA authority. The program ran for years before the Snowden disclosures changed public awareness.",                                                             upvotes:1842, comments:214,  credible:78, debunked:22, tags:["NSA","FOIA","Surveillance"],                    premium:true },
  { id:"s7",  slug:"the-bilderberg-group-70-years-of-private-summits-between-heads-of-state-and-cent", type:"blog",     source:"Corbett Report",             sourceUrl:"https://www.corbettreport.com",    time:"7h ago",  topic:"Finance & Power",              region:"Global",title:"The Bilderberg Group: 70 Years of Private Summits Between Heads of State and Central Bankers",             summary:"Annual meetings include sitting prime ministers, NATO chiefs, and major media owners  -  with no press, no published minutes, and no public accountability whatsoever.",                                                                                       upvotes:3201, comments:441,  credible:71, debunked:29, tags:["Bilderberg","Power","Finance"],                  premium:true },
  { id:"s8",  slug:"gobekli-tepe-12000-year-old-megalithic-temple-complex-rewrites-accepted-timeline", type:"podcast",  source:"The Why Files",              sourceUrl:"https://www.youtube.com/@TheWhyFiles",time:"8h ago",topic:"Ancient Civilizations",        region:"Global",title:"Gobekli Tepe: 12,000-Year-Old Megalithic Temple Complex Rewrites Accepted Timeline of Human Civilization", summary:"Gobekli Tepe in Turkey predates Stonehenge by 6,000 years and the Egyptian pyramids by 7,000 years  -  built before agriculture was established. The Why Files examines what this means for the accepted timeline of organized human civilization.",         upvotes:5821, comments:891,  credible:89, debunked:11, tags:["Gobekli Tepe","Ancient","Timeline"],             premium:false },
  { id:"s9",  slug:"genesis-6-and-the-nephilim-cross-cultural-evidence-of-giant-beings-in-over-200-a", type:"research", source:"Genesis 6 Ministries",      sourceUrl:"https://gen6giants.com",           time:"9h ago",  topic:"Giants & Nephilim",            region:"Global",title:"Genesis 6 and the Nephilim: Cross-Cultural Evidence of Giant Beings in Over 200 Ancient Traditions",      summary:"Researchers have catalogued over 200 ancient cultures from Mesopotamia to the Americas to Polynesia that contain independent legends of giant beings living among early humans, many with striking structural parallels to the Genesis account.",             upvotes:5820, comments:891,  credible:60, debunked:40, tags:["Nephilim","Genesis","Cross-Cultural","Giants"], premium:true },
  { id:"s10", slug:"suppressed-gospels-and-texts-excluded-at-the-council-of-nicaea-in-325-ad-vatican", type:"archive",  source:"Vatican Apostolic Archive",  sourceUrl:"https://www.archivioapostolicovaticano.va",time:"10h ago",topic:"Biblical & Religious Records",region:"Vatican",title:"Suppressed Gospels and Texts Excluded at the Council of Nicaea in 325 AD  -  Vatican Archives",             summary:"The Council of Nicaea in 325 AD determined the official Biblical canon. Dozens of gospels including the Gospel of Thomas and the Book of Enoch were excluded. Many remain in the Vatican Archives, partially accessible since 1881.",                       upvotes:7410, comments:1204, credible:82, debunked:18, tags:["Vatican","Canon","Suppressed","Nicaea"],          premium:true },
  { id:"s11", slug:"orca-and-dolphin-long-term-memory-evidence-of-multigenerational-cultural-knowled", type:"research", source:"Journal of Cetacean Research",sourceUrl:"https://iwc.int",                time:"11h ago", topic:"Animal Intelligence",           region:"Global",title:"Orca and Dolphin Long-Term Memory: Evidence of Multigenerational Cultural Knowledge and Grief",            summary:"Studies document orcas maintaining grudges against specific boats for decades, grieving dead calves for weeks, and transmitting dialect-specific vocalizations across four generations  -  qualifying as cultural identity by scientific definition.",          upvotes:3918, comments:445,  credible:85, debunked:15, tags:["Orca","Dolphins","Memory","Culture"],          premium:true },
  { id:"s12", slug:"cia-vault-7-umbrage-malware-library-designed-to-frame-other-nations-for-cyberatt", type:"archive",  source:"WikiLeaks",                  sourceUrl:"https://wikileaks.org",            time:"12h ago", topic:"Surveillance",                 region:"Global",title:"CIA Vault 7  -  UMBRAGE: Malware Library Designed to Frame Other Nations for Cyberattacks",                 summary:"The CIA maintained hacking tools designed to leave digital fingerprints matching other nations  -  fundamentally challenging attribution certainty in all major cyberattacks since 2010.",                                                                    upvotes:9200, comments:1841, credible:88, debunked:12, tags:["CIA","Cyber","False Attribution"],               premium:true },
  { id:"s13", slug:"jeffrey-epstein-no-verified-income-source-private-islands-access-to-world-leader", type:"news",    source:"Miami Herald",               sourceUrl:"https://www.miamiherald.com",      time:"13h ago", topic:"Unresolved Events",             region:"USA",  title:"Jeffrey Epstein: No Verified Income Source, Private Islands, Access to World Leaders  -  Full Investigation", summary:"The Herald's investigation found Epstein had no verifiable business generating his wealth, yet maintained relationships with heads of state globally. His 2019 death was ruled suicide with both prison guards asleep and cameras malfunctioning.", upvotes:6821, comments:1204, credible:86, debunked:14, tags:["Epstein","Intelligence","Unsealed"],            premium:false },
  { id:"s14", slug:"fbi-director-lab-leak-is-most-credible-covid-19-origin-declassified-intelligence", type:"news",    source:"Wall Street Journal",        sourceUrl:"https://www.wsj.com",              time:"14h ago", topic:"Health & Science",              region:"USA",  title:"FBI Director: Lab Leak Is Most Credible COVID-19 Origin  -  Declassified Intelligence Assessment",           summary:"FBI Director Wray stated the Bureau assessed SARS-CoV-2 most likely originated from a lab incident. The DOE reached the same conclusion independently. FOIA emails show NIH officials tried to suppress this hypothesis in early 2020.",              upvotes:7910, comments:1480, credible:74, debunked:26, tags:["COVID","Lab Leak","Declassified"],               premium:true },
  { id:"s15", slug:"university-of-alaska-fairbanks-wtc-7-collapse-could-not-have-been-caused-by-fire", type:"research",source:"AE911Truth / UAF Study",    sourceUrl:"https://www.ae911truth.org",       time:"15h ago", topic:"Unresolved Events",             region:"USA",  title:"University of Alaska Fairbanks: WTC 7 Collapse Could Not Have Been Caused by Fire  -  4-Year Engineering Study", summary:"The UAF study concluded WTC Building 7  -  not struck by a plane  -  could only have collapsed through near-simultaneous failure of every column. The official NIST report attributed it to fire alone.", upvotes:7210, comments:1842, credible:65, debunked:35, tags:["WTC7","Engineering","9/11"],                    premium:true },
  { id:"s16", slug:"operation-paperclip-1600-nazi-scientists-secretly-transferred-to-the-us-after-ww", type:"archive", source:"NSA Archive",               sourceUrl:"https://nsarchive.gwu.edu",         time:"16h ago", topic:"Government & Intelligence",     region:"USA",  title:"Operation Paperclip: 1,600 Nazi Scientists Secretly Transferred to the U.S. After WWII  -  Full Document Release", summary:"After WWII the U.S. military secretly recruited Nazi scientists and engineers. Wernher von Braun, an SS officer, became the chief architect of NASA's Apollo program. The full scope of transferred knowledge remains partially classified.", upvotes:4800, comments:721,  credible:97, debunked:3,  tags:["Paperclip","NASA","Declassified"],               premium:true },
  { id:"s17", slug:"twitter-files-fbi-communication-channels-resulted-in-suppression-of-accurate-rep", type:"news",    source:"The Intercept",             sourceUrl:"https://theintercept.com",          time:"17h ago", topic:"Media & Disclosure",            region:"USA",  title:"Twitter Files: FBI Communication Channels Resulted in Suppression of Accurate Reporting  -  Internal Documents", summary:"Internal documents showed sustained FBI communication with Twitter trust-and-safety teams. Several suppression requests targeted stories that later proved accurate, including the Hunter Biden laptop story.", upvotes:8841, comments:2102, credible:81, debunked:19, tags:["Twitter","FBI","Censorship"],                  premium:true },
  { id:"s18", slug:"the-federal-reserve-a-private-banking-cartel-that-has-never-been-independently-a", type:"blog",    source:"Corbett Report",            sourceUrl:"https://www.corbettreport.com",     time:"18h ago", topic:"Finance & Power",               region:"USA",  title:"The Federal Reserve: A Private Banking Cartel That Has Never Been Independently Audited in 110 Years",      summary:"The Federal Reserve has never undergone a full independent audit despite controlling U.S. monetary policy. The Fed Transparency Act has been repeatedly blocked. A partial audit in 2011 revealed $16 trillion in secret emergency loans.", upvotes:5200, comments:714,  credible:82, debunked:18, tags:["Federal Reserve","Banking","Audit"],              premium:true },
  { id:"s19", slug:"ohio-mound-builders-giant-skeletons-7-9-feet-tall-documented-by-archaeologists-i", type:"research",source:"Newspaper Archive",         sourceUrl:"https://newspaperarchive.com",      time:"19h ago", topic:"Giants & Nephilim",             region:"USA",  title:"Ohio Mound Builders: Giant Skeletons 7-9 Feet Tall Documented by Archaeologists in 1800s  -  Full Archive",   summary:"The Smithsonian's own Bureau of Ethnology Annual Reports from the 1870s-1890s document giant humanoid skeletal remains found in burial mounds across Ohio, Indiana, and West Virginia  -  some exceeding 9 feet. None are publicly accessible today.", upvotes:6200, comments:980,  credible:62, debunked:38, tags:["Giants","Ohio","Mounds","Smithsonian"],           premium:false },
  { id:"s20", slug:"numbers-1333-the-israelite-spies-report-giants-in-canaan-we-were-like-grasshoppe", type:"research",source:"Gen6 Giants",               sourceUrl:"https://www.gen6giants.com",        time:"20h ago", topic:"Giants & Nephilim",             region:"USA",  title:"Numbers 13:33  -  The Israelite Spies Report Giants in Canaan: 'We Were Like Grasshoppers in Our Own Sight'", summary:"The Biblical account of Israelite spies reporting Nephilim in Canaan provides geographic and descriptive detail that researchers cross-reference with ancient Canaanite archaeology. The Anakim and Rephaim are named separately from the Nephilim.", upvotes:4100, comments:621,  credible:55, debunked:45, tags:["Nephilim","Numbers","Canaan","Biblical"],          premium:true },
  { id:"s21", slug:"the-smithsonian-giant-cover-up-hundreds-of-19th-century-reports-and-where-the-re", type:"podcast", source:"The Why Files",             sourceUrl:"https://www.youtube.com/@TheWhyFiles",time:"21h ago",topic:"Giants & Nephilim",             region:"USA",  title:"The Smithsonian Giant Cover-Up: Hundreds of 19th Century Reports and Where the Remains Went",               summary:"The Why Files investigates the documented trail of giant skeletal discoveries in the American Midwest and Southeast  -  from initial newspaper accounts to Smithsonian collection records  -  and the complete absence of any remains in publicly accessible collections.", upvotes:7100, comments:1102, credible:61, debunked:39, tags:["Giants","Smithsonian","Cover-up","USA"],         premium:true },
  { id:"s22", slug:"us-navy-dolphin-research-program-decades-of-classified-intelligence-on-dolphin-c", type:"research",source:"NOAA Marine Research",      sourceUrl:"https://oceanexplorer.noaa.gov",    time:"22h ago", topic:"Animal Intelligence",           region:"USA",  title:"U.S. Navy Dolphin Research Program: Decades of Classified Intelligence on Dolphin Cognition and Sonar",    summary:"The U.S. Navy's Marine Mammal Program, based in San Diego, has studied dolphin intelligence and sonar capabilities since the 1960s. Declassified portions reveal communication sophistication that exceeds most civilian research benchmarks.", upvotes:3400, comments:412,  credible:79, debunked:21, tags:["Dolphins","Navy","Sonar","Intelligence"],         premium:true },
  { id:"s23", slug:"bottlenose-dolphins-using-marine-sponges-as-tools-cultural-transmission-confirme", type:"research",source:"Shark Bay Research Station", sourceUrl:"https://www.monkeymia.com.au",      time:"23h ago", topic:"Animal Intelligence",           region:"Global", title:"Bottlenose Dolphins Using Marine Sponges as Tools  -  Cultural Transmission Confirmed Across 3 Generations",  summary:"Dolphins at Shark Bay, Australia use marine sponges to protect their snouts while foraging  -  a behavior taught exclusively mother to daughter and documented across three generations, meeting the scientific definition of cultural transmission.", upvotes:2900, comments:318,  credible:91, debunked:9,  tags:["Dolphins","Tool Use","Culture","Research"],       premium:true },
  { id:"s24", slug:"the-great-pyramid-internal-temperature-remains-a-constant-68-degrees-regardless-", type:"research",source:"Graham Hancock",            sourceUrl:"https://grahamhancock.com",          time:"1d ago",  topic:"Lost Technology",               region:"Egypt", title:"The Great Pyramid's Internal Temperature Remains a Constant 68 degreesF Regardless of Outside Temperature",        summary:"The Great Pyramid of Giza maintains a constant internal temperature of 68 degreesF (20 degreesC)  -  the same as the Earth's mean temperature  -  regardless of external conditions. Engineers have been unable to explain this thermodynamic property using conventional construction theory.", upvotes:5100, comments:721,  credible:72, debunked:28, tags:["Pyramid","Egypt","Temperature","Lost Tech"],      premium:true },
  { id:"s25", slug:"precision-stonework-at-the-valley-temple-of-khafre-cuts-and-tolerances-that-matc", type:"research",source:"UnchartedX",                sourceUrl:"https://www.youtube.com/@UnchartedX1",time:"1d ago", topic:"Lost Technology",               region:"Egypt", title:"Precision Stonework at the Valley Temple of Khafre: Cuts and Tolerances That Match Modern CNC Machining",  summary:"Field researcher Ben van Kerkwyk documents stone blocks at the Valley Temple displaying interior angles, surface flatness, and cut tolerances within fractions of a millimeter  -  matching modern Computer Numerical Control machining specifications that were not available until the 20th century.", upvotes:6300, comments:891,  credible:68, debunked:32, tags:["Egypt","Machining","Lost Tech","Precision"],       premium:true },
  { id:"s26", slug:"the-council-on-foreign-relations-100-years-of-shaping-us-foreign-policy-from-out", type:"archive", source:"Corbett Report",            sourceUrl:"https://www.corbettreport.com",     time:"1d ago",  topic:"Secret Societies",              region:"USA",  title:"The Council on Foreign Relations: 100 Years of Shaping U.S. Foreign Policy From Outside Government",        summary:"The CFR, founded in 1921, has counted virtually every U.S. Secretary of State, CIA Director, and National Security Advisor among its members. Its own publications acknowledge its role in setting the foreign policy agenda before elections determine who implements it.", upvotes:4200, comments:581,  credible:74, debunked:26, tags:["CFR","Foreign Policy","Deep State"],              premium:true },
  { id:"s27", slug:"seymour-hersh-investigation-us-navy-divers-planted-explosives-on-nord-stream-pip", type:"news",    source:"Consortium News",           sourceUrl:"https://consortiumnews.com",        time:"1d ago",  topic:"Geopolitics & Deep State",      region:"Global", title:"Seymour Hersh Investigation: U.S. Navy Divers Planted Explosives on Nord Stream Pipeline During NATO Exercise", summary:"Pulitzer Prize-winning journalist Seymour Hersh, citing a senior U.S. official, reported that Navy divers planted explosives on Nord Stream during a NATO exercise in June 2022. The story was entirely ignored by major U.S. outlets despite Hersh's documented track record.", upvotes:5811, comments:921,  credible:70, debunked:30, tags:["Nordstream","NATO","Sabotage","Disputed"],         premium:true },
  { id:"s28", slug:"chuck-missler-the-integrity-of-the-genetic-bloodline-why-genesis-6-giants-were-t", type:"research",source:"Koinonia House",            sourceUrl:"https://www.khouse.org",             time:"2d ago",  topic:"Biblical & Religious Records",  region:"USA",  title:"Chuck Missler: The Integrity of the Genetic Bloodline  -  Why Genesis 6 Giants Were the Reason for the Flood", summary:"Biblical scholar Chuck Missler's research argues that the Nephilim corruption of the human genetic line  -  not merely moral corruption  -  was the reason God initiated the flood. He cross-references Genesis 6 with Enoch, Numbers 13, and the Dead Sea Scrolls.", upvotes:4800, comments:712,  credible:58, debunked:42, tags:["Missler","Genesis","Flood","Nephilim","Biblical"],   premium:true },
  { id:"s29", slug:"peruvian-elongated-skulls-dna-testing-shows-non-human-mitochondrial-dna-in-parac", type:"research",source:"L.A. Marzulli Blog",        sourceUrl:"https://lamarzulli.net",             time:"2d ago",  topic:"Giants & Nephilim",             region:"USA",  title:"Peruvian Elongated Skulls  -  DNA Testing Shows Non-Human Mitochondrial DNA in Paracas Specimens",           summary:"DNA analysis conducted on elongated skulls from Paracas, Peru reportedly showed mitochondrial DNA with mutations unknown in any human, primate, or animal. The researcher who conducted the analysis has been unable to get results peer-reviewed through conventional journals.", upvotes:7100, comments:1204, credible:44, debunked:56, tags:["Paracas","Skulls","DNA","Giants","Peru"],           premium:true },
  { id:"s30", slug:"cointelpro-the-fbi-documented-campaign-to-destroy-civil-rights-leaders-anti-war-", type:"podcast", source:"Stuff They Don't Want You to Know",sourceUrl:"https://www.iheart.com/podcast/182-stuff-they-dont-want-you-17913675/",time:"2d ago",topic:"Government & Intelligence",region:"USA",title:"COINTELPRO: The FBI's Documented Campaign to Destroy Civil Rights Leaders, Anti-War Groups, and Political Dissidents", summary:"COINTELPRO ran from 1956 to 1971. Declassified documents confirm the FBI used illegal surveillance, infiltration, fabricated evidence, and psychological warfare against the NAACP, SCLC, Black Panthers, SDS, and even the women's liberation movement.", upvotes:5400, comments:781,  credible:95, debunked:5,  tags:["COINTELPRO","FBI","Civil Rights","Declassified"],    premium:false },
  {id:"s31",slug:"myth-of-adapa-the-first-man-given-wisdom-but-denied-immortality-sumerian-primary",type:"archive", source:"Sacred Texts Archive",      sourceUrl:"https://sacred-texts.com/ane/adapa.htm",  time:"3h ago", topic:"Ancient Civilizations",       region:"Middle East",title:"Myth of Adapa: The First Man Given Wisdom but Denied Immortality  -  Sumerian Primary Text", summary:"The Adapa myth predates Genesis by thousands of years. Enki creates Adapa as humanity's first sage and commissioner of the Anunnaki, granting him wisdom but withholding eternal life. When sky-god Anu offers Adapa the bread and water of immortality, Enki's secret instructions cause Adapa to refuse. Researchers argue this is the original template for the Garden of Eden narrative.", upvotes:4800,comments:712, credible:72,debunked:28,tags:["Adapa","Enki","Anu","Anunnaki","Genesis"],    premium:false},
  {id:"s32",slug:"anki-enlil-and-the-anunnaki-council-the-original-divine-hierarchy-preserved-in-s",type:"research",source:"ETCSL Oxford University",   sourceUrl:"https://etcsl.orinst.ox.ac.uk",           time:"4h ago", topic:"Ancient Civilizations",       region:"Global",               title:"Anki, Enlil & the Anunnaki Council: The Original Divine Hierarchy Preserved in Sumerian Cuneiform", summary:"Sumerian tablets describe An (heaven) and Ki (earth) as cosmic parents. Their son Enlil separated heaven from earth. The Anunnaki  -  the heaven-earth council of gods  -  governed fate, created humanity, and survived the flood. These texts at Oxford's ETCSL structurally parallel the divine councils in Genesis, Enoch, and the Dead Sea Scrolls.", upvotes:3900,comments:521, credible:78,debunked:22,tags:["Anki","Enlil","Anunnaki","Sumerian"],premium:false},
  {id:"s33",slug:"the-anunnaki-sumerian-gods-genetic-engineers-or-extraterrestrial-visitors-all-th",type:"research",source:"Ancient Origins",           sourceUrl:"https://www.ancient-origins.net",         time:"5h ago", topic:"Ancient Civilizations",       region:"Global",               title:"The Anunnaki: Sumerian Gods, Genetic Engineers, or Extraterrestrial Visitors? All Theories Examined", summary:"The Anunnaki appear in thousands of tablets as the divine assembly who created humanity from clay and divine blood. Sitchin interpreted them as aliens from Nibiru who engineered Homo sapiens. Orthodox scholars read them as the Mesopotamian pantheon. The debate spans DNA manipulation, ancient astronaut theory, and the origin of civilization.", upvotes:7200,comments:1104,credible:55,debunked:45,tags:["Anunnaki","Sitchin","DNA","Ancient Aliens"], premium:false},
  {id:"s34",slug:"vatican-chronovisor-father-ernetti-time-viewing-device-built-with-enrico-fermi-h",type:"research",source:"Project Unredacted",        sourceUrl:"https://www.projectunredacted.com/cases/chronovisor-vatican-time-machine",time:"6h ago",topic:"Secret Societies",region:"Vatican",title:"Vatican Chronovisor: Father Ernetti's Time-Viewing Device  -  Built With Enrico Fermi, Hidden in the Archives", summary:"In 1972 Father Pellegrino Ernetti claimed he and 12 scientists including Enrico Fermi and Wernher von Braun built a device capturing electromagnetic echoes of past events. He claimed to witness Christ's crucifixion and a lost Roman play. The Vatican issued an excommunication decree against unauthorized use of such devices in 1988  -  an act researchers argue implies acknowledgment.", upvotes:6100,comments:981, credible:42,debunked:58,tags:["Chronovisor","Vatican","Time","Ernetti"],       premium:false},
  {id:"s35",slug:"sedona-vortex-sites-electrical-engineer-measures-magnetic-anomalies-eeg-and-magn",type:"research",source:"Sedona Anomalies Research", sourceUrl:"https://sedonanomalies.com",              time:"7h ago", topic:"Forbidden Science",           region:"USA",                title:"Sedona Vortex Sites: Electrical Engineer Measures Magnetic Anomalies  -  EEG and Magnetometer Data", summary:"Electrical engineer Benjamin Lonetree spent a decade measuring Sedona's vortex sites using magnetometers and portable EEG devices. His research documents measurable outflows of magnetic energy correlated with human brainwave changes. The geology  -  high iron oxide sandstone, volcanic basalt with 5-20% quartz  -  may genuinely affect human consciousness.", upvotes:3400,comments:441, credible:61,debunked:39,tags:["Sedona","Electromagnetic","Vortex","Consciousness"],premium:false},
  {id:"s36",slug:"george-church-harvard-first-book-encoded-in-dna-70-billion-copies-crispr-and-syn",type:"research",source:"George Church Lab  -  Harvard",sourceUrl:"https://arep.med.harvard.edu",           time:"8h ago", topic:"Forbidden Science",           region:"USA",                title:"George Church (Harvard): First Book Encoded in DNA  -  70 Billion Copies. CRISPR & Synthetic Biology", summary:"Harvard geneticist George Church encoded his book Regenesis entirely in DNA  -  70 billion copies fitting on a thumbnail. His lab pioneered CRISPR gene editing, Neanderthal DNA reconstruction research, and the Personal Genome Project. He has speculated publicly about de-extincting Neanderthals and reversing aging through targeted gene therapy.", upvotes:5100,comments:721, credible:91,debunked:9, tags:["DNA","CRISPR","George Church","Synthetic Biology"],premium:false},
  {id:"s37",slug:"bruce-lipton-epigenetics-your-beliefs-change-gene-expression-dna-is-not-your-des",type:"research",source:"Bruce Lipton  -  brucelipton.com",sourceUrl:"https://www.brucelipton.com",         time:"9h ago", topic:"Forbidden Science",           region:"USA",                title:"Bruce Lipton: Epigenetics  -  Your Beliefs Change Gene Expression. DNA Is Not Your Destiny", summary:"Former Stanford cell biologist Bruce Lipton's research shows that the environment outside the cell  -  including thoughts, beliefs, and electromagnetic signals  -  controls which genes switch on or off. This directly challenges genetic determinism and suggests consciousness shapes biology at the molecular level.", upvotes:4800,comments:641, credible:74,debunked:26,tags:["Epigenetics","DNA","Lipton","Consciousness"],   premium:false},
  {id:"s38",slug:"vatican-archives-85-kilometers-of-shelving-hidden-gospels-galileo-trial-nazi-con",type:"archive", source:"Vatican Apostolic Archive",  sourceUrl:"https://www.archivioapostolicovaticano.va",time:"10h ago",topic:"Biblical & Religious Records",region:"Vatican",          title:"Vatican Archives: 85 Kilometers of Shelving  -  Hidden Gospels, Galileo's Trial, Nazi Concordats, Pre-Nicaean Texts", summary:"The Vatican Apostolic Archive holds 85 kilometers of shelving. It contains Galileo's trial records, Nazi concordat documents, Henry VIII's annulment request, and thousands of inaccessible texts. Researchers believe ancient documents about the Nephilim, Mary Magdalene, and pre-canonical gospels remain sealed to the public.", upvotes:6800,comments:1021,credible:77,debunked:23,tags:["Vatican","Archives","Hidden","Gospels"],        premium:true},
  {id:"s39",slug:"gregg-braden-the-god-code-ancient-name-encoded-in-every-human-dna-base-pair-sequ",type:"research",source:"Gregg Braden Official",      sourceUrl:"https://www.greggbraden.com",            time:"11h ago",topic:"Forbidden Science",           region:"USA",                title:"Gregg Braden: The God Code  -  Ancient Name Encoded in Every Human DNA Base Pair Sequence", summary:"Gregg Braden analyzed the chemical elements of DNA base pairs against ancient Hebrew letter-number values and claims the phrase meaning 'God Eternal Within the Body' is encoded in every strand of human DNA. His research bridges quantum physics, ancient scripture, and molecular biology  -  presenting DNA as cosmic message.", upvotes:5200,comments:812, credible:45,debunked:55,tags:["DNA","God Code","Braden","Frequency"],           premium:true},
  {id:"s40",slug:"dolores-cannon-qhht-subjects-under-deep-hypnosis-independently-describe-identica",type:"research",source:"Dolores Cannon Archive",     sourceUrl:"https://dolorescannon.com",              time:"12h ago",topic:"Forbidden Science",           region:"USA",                title:"Dolores Cannon QHHT: Subjects Under Deep Hypnosis Independently Describe Identical Accounts of Atlantis, DNA Modification, and Soul Origins", summary:"Over 50 years of Quantum Healing Hypnosis Technique sessions, Dolores Cannon documented subjects independently describing identical information about Atlantis, alien intervention in human DNA, and life between lives. Her 5-volume Convoluted Universe series catalogs thousands of cross-corroborating accounts that she argued cannot be explained by suggestion alone.", upvotes:4900,comments:781, credible:48,debunked:52,tags:["QHHT","Cannon","Past Lives","DNA","Atlantis"],   premium:true},
  {id:"s41",slug:"billy-carson-the-emerald-tablets-of-thoth-15-tablets-written-by-an-atlantean-pri",type:"research",source:"4biddenknowledge",           sourceUrl:"https://www.4biddenknowledge.com",       time:"13h ago",topic:"Ancient Civilizations",       region:"Global",               title:"Billy Carson: The Emerald Tablets of Thoth  -  15 Tablets Written by an Atlantean Priest-King 36,000 BCE", summary:"Billy Carson's analysis identifies Thoth (Hermes Trismegistus) as an Atlantean who fled to Egypt and built the Great Pyramid. The tablets describe stargates, the Halls of Amenti beneath the pyramid, zero-point energy, and consciousness as the fundamental substrate of reality. Carson cross-references with Sumerian tablets, quantum mechanics, and neuroscience.", upvotes:5800,comments:891, credible:50,debunked:50,tags:["Emerald Tablets","Thoth","Atlantis","Anunnaki"],premium:true},
  {id:"s42",slug:"the-gospel-of-mary-magdalene-suppressed-first-century-text-shows-her-as-jesus-cl",type:"blog",    source:"Ancient Origins",            sourceUrl:"https://www.ancient-origins.net",       time:"14h ago",topic:"Biblical & Religious Records",region:"Global",               title:"The Gospel of Mary Magdalene: Suppressed First-Century Text Shows Her as Jesus's Closest Disciple and Primary Teacher", summary:"The Gospel of Mary Magdalene, discovered in Cairo in 1896, depicts her receiving secret teachings from Jesus about matter, sin, and the soul  -  and transmitting these to the apostles over Peter's objection. Early church scholars argue this gospel was suppressed because it positioned a woman as the primary bearer of Jesus's esoteric teachings.", upvotes:5400,comments:821, credible:71,debunked:29,tags:["Mary Magdalene","Gospel","Suppressed","Gnostic"],premium:true},
  {id:"s43",slug:"heartmath-institute-the-heart-electromagnetic-field-is-100x-stronger-than-the-br",type:"research",source:"HeartMath Institute",        sourceUrl:"https://www.heartmath.org/research/",   time:"15h ago",topic:"Forbidden Science",           region:"USA",                title:"HeartMath Institute: The Heart's Electromagnetic Field Is 100x Stronger Than the Brain  -  Research Confirmed", summary:"The HeartMath Institute's research shows the heart generates an electromagnetic field 100 times stronger in amplitude than the brain's and detectable several feet from the body. Their research suggests the heart transmits emotional information to every cell and can be measured affecting others in proximity  -  a finding with implications for energy healing and consciousness studies.", upvotes:4100,comments:561, credible:78,debunked:22,tags:["HeartMath","Electromagnetic","Consciousness","Heart"],premium:true},
  {id:"s44",slug:"bitten-congress-ordered-investigation-into-whether-dod-weaponized-ticks-plum-isl",type:"research",source:"Kris Newby / BITTEN Files",  sourceUrl:"https://krisnewby.substack.com",        time:"1h ago", topic:"Health & Science",            region:"USA",                title:"BITTEN: Congress Ordered Investigation Into Whether DoD Weaponized Ticks  -  Plum Island, Fort Detrick & Lyme Disease Origins", summary:"In 2019 Congress passed an amendment ordering the DoD Inspector General to investigate whether the military weaponized ticks and other insects as bioweapons between 1950-1975 and whether any were accidentally released. Science writer Kris Newby's book BITTEN documents interviews with Willy Burgdorfer  -  who discovered the Lyme bacterium  -  and evidence linking Plum Island, just 13 miles from Lyme CT, to Cold War bioweapons tick experiments.",upvotes:6200,comments:980, credible:65,debunked:35,tags:["Lyme Disease","Ticks","Bioweapons","Plum Island"],premium:false},
  {id:"s45",slug:"vaers-database-over-2-million-adverse-event-reports-filed-since-1990-what-the-da",type:"news",    source:"VAERS / HHS",                 sourceUrl:"https://vaers.hhs.gov",                time:"2h ago", topic:"Health & Science",            region:"USA",                title:"VAERS Database: Over 2 Million Adverse Event Reports Filed Since 1990  -  What the Data Does and Does Not Show", summary:"The Vaccine Adverse Event Reporting System, managed jointly by the FDA and CDC, has received over 2 million reports of adverse events following vaccination since 1990. Experts debate what the data reveals vs. what requires further investigation. Congress mandated VAERS through the 1986 National Childhood Vaccine Injury Act after acknowledging vaccines can cause injury.",upvotes:5800,comments:1102,credible:71,debunked:29,tags:["VAERS","Vaccines","FDA","CDC","Adverse Events"],premium:false},
  {id:"s46",slug:"lab-grown-meat-uses-immortalized-cells-mit-cancer-biologist-they-are-unmistakabl",type:"research",source:"Food & Environment Reporting Network",sourceUrl:"https://thefern.org",          time:"3h ago", topic:"Health & Science",            region:"USA",                title:"Lab-Grown Meat Uses Immortalized Cells  -  MIT Cancer Biologist: They Are 'Unmistakably More Like Cancer Cells'", summary:"The Food and Environment Reporting Network's investigation revealed that cultured meat companies use 'immortalized' cells  -  cells that divide indefinitely by bypassing normal biological limits. MIT cancer biologist Robert Weinberg stated these cells 'have already completed one of the prerequisites to becoming a cancer cell.' The FAO and WHO identified 53 potential hazards in cultured meat production.",upvotes:5400,comments:821, credible:72,debunked:28,tags:["Lab Meat","Fake Meat","Cancer","GMO","Food Safety"],premium:false},
  {id:"s47",slug:"beyond-impossible-the-truth-behind-the-fake-meat-industry-wef-harvard-and-the-pu",type:"research",source:"Children's Health Defense",   sourceUrl:"https://childrenshealthdefense.org",    time:"4h ago", topic:"Health & Science",            region:"USA",                title:"Beyond Impossible: The Truth Behind the Fake Meat Industry  -  WEF, Harvard, and the Push to End Natural Meat", summary:"A 2024 systematic review of 45 studies and 9.8 million participants confirmed that ultra-processed food consumption is directly associated with 32 adverse health parameters. Lab-grown and fake meat are categorized as ultra-processed food. Critics argue the push toward fake meat serves financial and control agendas more than environmental or health goals.",upvotes:4900,comments:741, credible:61,debunked:39,tags:["Fake Meat","WEF","Ultra-processed","Health"],premium:false},
  {id:"s48",slug:"puma-punku-100-ton-stone-blocks-cut-with-cnc-level-precision-no-metal-tools-avai",type:"research",source:"UnchartedX Field Research",   sourceUrl:"https://www.youtube.com/@UnchartedX1", time:"5h ago", topic:"Lost Technology",             region:"South America",        title:"Puma Punku: 100-Ton Stone Blocks Cut With CNC-Level Precision  -  No Metal Tools Available at the Time", summary:"Puma Punku in Bolivia features massive andesite stone blocks with cuts that modern engineers compare to CNC machining tolerances. Andesite is rated 6-7 on the Mohs hardness scale  -  harder than any copper tool available to the Tiwanaku civilization. Field researchers document drill holes of identical depth and spacing that stonemasons say they could not replicate today without diamond-tipped power tools.",upvotes:7100,comments:1102,credible:68,debunked:32,tags:["Puma Punku","Lost Tech","Ancient","CNC","Bolivia"],premium:false},
  {id:"s49",slug:"baalbek-the-1200-ton-stone-of-the-pregnant-woman-no-modern-crane-can-lift-it",type:"research",source:"Ancient Code",                 sourceUrl:"https://www.ancient-code.com",         time:"6h ago", topic:"Lost Technology",             region:"Lebanon Israel / Middle East",title:"Baalbek: The 1,200-Ton Stone of the Pregnant Woman  -  No Modern Crane Can Lift It", summary:"The quarry at Baalbek, Lebanon contains the largest known worked stones in history  -  including the Stone of the Pregnant Woman at 1,200 tons. No crane in the world today can lift a single Baalbek foundation stone. The Roman-era temple was built on top of a far older megalithic foundation whose origin and construction method remain entirely unexplained.",upvotes:6400,comments:921, credible:74,debunked:26,tags:["Baalbek","Megalithic","Lost Tech","Lebanon"],premium:false},
  {id:"s50",slug:"the-younger-dryas-impact-a-comet-strike-12800-years-ago-destroyed-an-advanced-gl",type:"research",source:"Graham Hancock / Ancient Apocalypse",sourceUrl:"https://grahamhancock.com",     time:"7h ago", topic:"Hidden History",              region:"Global",               title:"The Younger Dryas Impact: A Comet Strike 12,800 Years Ago Destroyed an Advanced Global Civilization", summary:"A growing body of scientific evidence  -  including nano-diamonds, platinum anomalies, and burned layers found on four continents  -  supports the Younger Dryas Impact hypothesis: that a comet strike around 12,800 BCE caused a catastrophic global event that destroyed an advanced pre-ice age civilization. This explains why megalithic sites appear globally with no developmental sequence.",upvotes:5900,comments:881, credible:62,debunked:38,tags:["Younger Dryas","Comet","Lost Civilization","Graham Hancock"],premium:false},
  {id:"s51",slug:"the-osireion-at-abydos-built-before-the-pyramids-massive-granite-structure-defie",type:"research",source:"Ancient Origins",              sourceUrl:"https://www.ancient-origins.net",      time:"8h ago", topic:"Ancient Civilizations",       region:"Egypt",               title:"The Osireion at Abydos: Built Before the Pyramids? Massive Granite Structure Defies Official Chronology", summary:"The Osireion  -  discovered beneath the Temple of Seti I at Abydos  -  is built from massive red granite blocks in a style completely different from New Kingdom Egyptian construction. Geologist Robert Schoch and others argue the building style matches structures contemporaneous with the Great Sphinx, suggesting an origin thousands of years before Seti I. No inscriptions, no dedications  -  just massive precision stonework.",upvotes:4800,comments:712, credible:66,debunked:34,tags:["Osireion","Egypt","Abydos","Lost Tech","Schoch"],premium:true},
  {id:"s52",slug:"sacred-geometry-in-ancient-architecture-the-same-mathematical-constants-encoded-",type:"research",source:"Randall Carlson / Kosmographia",sourceUrl:"https://randallcarlson.com",         time:"9h ago", topic:"Hidden History",              region:"Global",               title:"Sacred Geometry in Ancient Architecture: The Same Mathematical Constants Encoded Worldwide  -  Independently", summary:"Researcher Randall Carlson documents that ancient sites worldwide  -  from the Great Pyramid to Angkor Wat to Stonehenge  -  encode identical mathematical relationships: Pi, Phi (golden ratio), the precession of the equinoxes, and the dimensions of the Earth itself. The probability of this occurring by independent coincidence is astronomically small, suggesting either a common advanced source civilization or a lost mathematical tradition transmitted globally.",upvotes:5300,comments:781, credible:61,debunked:39,tags:["Sacred Geometry","Phi","Pyramid","Precession","Randall Carlson"],premium:true},
  {id:"s53",slug:"the-sumerian-king-list-rulers-who-reigned-for-thousands-of-years-before-the-floo",type:"research",source:"World History Encyclopedia",  sourceUrl:"https://www.worldhistory.org",          time:"10h ago",topic:"Ancient Civilizations",       region:"Global",               title:"The Sumerian King List: Rulers Who Reigned for Thousands of Years Before the Flood  -  Cuneiform Primary Source", summary:"The Sumerian King List, a cuneiform document discovered at Nippur, records kings who ruled for tens of thousands of years before a great flood. After the flood, lifespans drop dramatically to human-normal lengths. Researchers debate whether this records actual dynasties, mythological time, or evidence of a pre-flood civilization. It is the oldest known historical document to reference the flood narrative.",upvotes:4600,comments:621, credible:70,debunked:30,tags:["Sumerian","King List","Flood","Cuneiform","Pre-Flood"],premium:false},
  {id:"s54",slug:"ancient-beings-as-engineers-the-gobekli-tepe-builders-knew-astronomy-geometry-an",type:"research",source:"Gaia / Billy Carson",          sourceUrl:"https://www.gaia.com",                 time:"11h ago",topic:"Ancient Civilizations",       region:"Global",               title:"Ancient Beings as Engineers: The Gobekli Tepe Builders Knew Astronomy, Geometry, and Built Before Agriculture Existed", summary:"New research at Gobekli Tepe confirms the 12,000-year-old site encodes star maps  -  specifically Deneb, Arcturus, and the Pleiades  -  in its pillar arrangements. The builders had sophisticated astronomical knowledge, geometric precision, and organized labor capability  -  all predating the supposed invention of agriculture by 1,000 years. This overturns the model of a linear progression from primitive to advanced.",upvotes:5700,comments:841, credible:82,debunked:18,tags:["Gobekli Tepe","Astronomy","Ancient Beings","Pre-History"],premium:false},
  {id:"s55",slug:"zecharia-sitchin-the-anunnaki-genetically-engineered-homo-sapiens-250000-years-a",type:"research",source:"Sitchin Archive",              sourceUrl:"https://sitchin.com",                  time:"12h ago",topic:"Ancient Civilizations",       region:"Global",               title:"Zecharia Sitchin: The Anunnaki Genetically Engineered Homo Sapiens 250,000 Years Ago  -  Sumerian Texts Decoded", summary:"Zecharia Sitchin's translations of Sumerian texts describe the Anunnaki creating humanity through genetic engineering  -  mixing their DNA with Homo erectus  -  to produce a slave race for mining gold. The Atrahasis Epic parallels the Genesis creation and flood accounts almost word for word. Mainstream archaeologists reject Sitchin's translations; alternative researchers point to the structural parallels as too precise to dismiss.",upvotes:6800,comments:1041,credible:45,debunked:55,tags:["Anunnaki","Sitchin","Genetic Engineering","Creation","Sumerian"],premium:true},
  {id:"s56",slug:"the-aryan-mystery-secret-societies-blood-types-and-the-hidden-history-of-humanit",type:"research",source:"Robert Sepehr  -  YouTube",      sourceUrl:"https://www.youtube.com/@RobertSepehr", time:"13h ago",topic:"Hidden History",              region:"Global",               title:"The Aryan Mystery: Secret Societies, Blood Types, and the Hidden History of Humanity's True Origins", summary:"Anthropologist Robert Sepehr's research examines the role of blood type distribution, genetic haplogroups, and ancient migration patterns in understanding humanity's hidden origins. He explores connections between ancient Aryan peoples, Atlantis, the Vedic traditions, and the origins of secret societies  -  arguing that mainstream history has deliberately suppressed knowledge of pre-Flood civilizations.",upvotes:4200,comments:601, credible:48,debunked:52,tags:["Aryan","Blood Type","Haplogroup","Hidden History","Sepehr"],premium:true},
  {id:"s57",slug:"us-navy-marine-mammal-program-classified-1967-1992-what-the-black-budget-dolphin",type:"archive", source:"Wikipedia / USNI Proceedings",sourceUrl:"https://en.wikipedia.org/wiki/United_States_Navy_Marine_Mammal_Program",time:"1h ago",topic:"Animal Intelligence",region:"USA",title:"US Navy Marine Mammal Program: Classified 1967-1992  -  What the Black Budget Dolphin Program Actually Did", summary:"The US Navy Marine Mammal Program (NMMP) began in 1960 studying dolphin hydrodynamics for torpedo and submarine design. By 1963 it became an active training program. In 1967 it was classified as a black budget program. Declassified only in 1992  -  but operational details remain sealed. At peak during the Reagan years: 150+ dolphins, $8M annual budget, deployed in 25 countries. Some researchers call it the Cetacean Intelligence Mission rather than its official name  -  suggesting the scope went far beyond mine detection.",upvotes:8200,comments:1401,credible:88,debunked:12,tags:["Navy","Dolphins","Classified","NMMP","Black Budget"],premium:false},
  {id:"s58",slug:"the-5-operational-dolphin-teams-mine-detection-swimmer-killing-devices-harbor-pa",type:"research",source:"History.com / Military History",sourceUrl:"https://www.history.com/articles/navy-marine-mammal-program-history-dolphins-sea-lions",time:"2h ago",topic:"Animal Intelligence",region:"USA",title:"The 5 Operational Dolphin Teams: Mine Detection, Swimmer Killing Devices, Harbor Patrol, and What They Won't Confirm", summary:"The Navy officially acknowledges five operational dolphin teams. MK-4 and MK-7 detect tethered and bottom mines. MK-8 clears landing corridors for troop insertions. MK-6 uses dolphins for anti-swimmer harbor defense  -  the dolphin approaches from behind and bumps a device onto the diver's air tank triggering an explosive buoy alert. Unconfirmed analyst claims describe carbonic acid injection devices mounted on dolphin heads  -  fired on contact with enemy divers. The Navy has never confirmed or denied the full scope of MK-6 offensive capabilities.",upvotes:7100,comments:1102,credible:74,debunked:26,tags:["NMMP","MK6","Swimmer","Mine","Dolphins","Combat"],premium:false},
  {id:"s59",slug:"cia-sent-scientist-james-fitzgerald-to-key-west-1964-classified-dolphin-lab-and-",type:"archive", source:"Military Marine Mammal Wikipedia / lflank.wordpress.com",sourceUrl:"https://en.wikipedia.org/wiki/Military_marine_mammal",time:"3h ago",topic:"Animal Intelligence",region:"USA",title:"CIA Sent Scientist James Fitzgerald to Key West 1964  -  Classified Dolphin Lab and the Intelligence Program Nobody Talks About", summary:"According to declassified sources, the CIA sent scientist James Fitzgerald to Key West, Florida in 1964 to establish a classified laboratory studying dolphins. The program ran parallel to the Navy NMMP  -  with the CIA angle focused on intelligence applications rather than mine detection. The lab's full scope, findings, and what happened to its research remain classified. This is the CIA's dolphin program that almost nobody knows existed alongside the Navy's.",upvotes:6800,comments:981,credible:62,debunked:38,tags:["CIA","Dolphins","James Fitzgerald","Key West","Classified"],premium:false},
  {id:"s60",slug:"dr-john-c-lilly-cia-funded-nasa-contracted-lsd-injecting-dolphin-researcher-who-",type:"research",source:"Supercluster / Vice",          sourceUrl:"https://www.supercluster.com/editorial/how-dolphins-on-lsd-shaped-the-search-for-extraterrestrial-intelligence",time:"4h ago",topic:"Animal Intelligence",region:"USA",title:"Dr. John C. Lilly: CIA-Funded, NASA-Contracted, LSD-Injecting Dolphin Researcher Who Founded the Science of Interspecies Communication", summary:"Dr. John C. Lilly  -  physician, neuroscientist, inventor of the isolation tank  -  opened the Communication Research Institute in St. Thomas in the 1960s funded by NASA and the CIA. NASA wanted a model for communicating with extraterrestrial intelligence. The CIA wanted dolphins as underwater spies. In 1964 Lilly began injecting dolphins with LSD to enhance communication  -  documented in a 1965 conference paper. Dolphin vocalizations increased dramatically. He co-founded the Order of the Dolphins with Carl Sagan. The CIA's interest in Lilly  -  through MK-Ultra era consciousness programs  -  has been confirmed in documents released decades later.",upvotes:9100,comments:1502,credible:82,debunked:18,tags:["Lilly","CIA","NASA","LSD","MK-Ultra","Dolphins","SETI"],premium:false},
  {id:"s61",slug:"vietnam-war-persian-gulf-iraq-war-2003-the-combat-deployments-of-us-military-dol",type:"research",source:"VeteranLife / USNavy",          sourceUrl:"https://veteranlife.com/military-history/marine-mammal-program",time:"5h ago",topic:"Animal Intelligence",region:"Global",title:"Vietnam War 1965-1975, Persian Gulf 1986-1988, Iraq War 2003: The Combat Deployments of US Military Dolphins That History Barely Covers", summary:"Navy dolphins were operationally deployed in Vietnam from 1965-1975 guarding ammunition piers from enemy divers. In the Persian Gulf they escorted Kuwaiti oil tankers and patrolled for mines during the Iran-Iraq War 1986-1988. In 2003 during the Iraq War K-Dog and other dolphins detected and marked over 100 anti-ship mines at the port of Umm Qasr  -  clearing the way for the initial troop landings. In 1996 six dolphins patrolled San Francisco Bay to protect the Republican National Convention. The Navy acknowledges deployments in 25 countries  -  the full list remains classified.",upvotes:7400,comments:1041,credible:91,debunked:9,tags:["Navy","Dolphins","Vietnam","Iraq","Persian Gulf","Combat"],premium:false},
  {id:"s62",slug:"soviet-and-russian-military-dolphins-sevastopol-iran-sale-arctic-bases-and-two-p",type:"research",source:"Historic Mysteries / Military Wiki",sourceUrl:"https://www.historicmysteries.com/history/military-marine-mammal/30639/",time:"6h ago",topic:"Animal Intelligence",region:"Global",title:"Soviet and Russian Military Dolphins: Sevastopol, Iran Sale, Arctic Bases, and Two Pens Placed at Ukraine Invasion Harbor", summary:"The Soviet Union ran a parallel dolphin program at Sevastopol, Crimea. Unlike the US program which denies offensive training, the Soviets are believed to have equipped dolphins with weapons. After the USSR collapsed the program transferred to Ukraine  -  which sold the dolphins and the chief trainer to Iran in 2000. Russia reactivated the program in 2012. After the 2014 Crimea annexation Russia took over Ukraine's remaining dolphins. When Russia invaded Ukraine in 2022, satellite imagery confirmed two dolphin pens placed at the entrance to Sevastopol harbor  -  the Black Sea's largest naval base  -  and additional pens at the secretive Arctic Olenya Guba facility.",upvotes:8600,comments:1301,credible:85,debunked:15,tags:["Russia","Soviet","Dolphins","Sevastopol","Ukraine","Military","Iran"],premium:false},
  {id:"s63",slug:"marine-mammal-protection-act-why-it-is-illegal-to-touch-feed-chase-or-attempt-to",type:"research",source:"NOAA Fisheries / LegalClarity",  sourceUrl:"https://www.fisheries.noaa.gov/marine-life-distress/frequent-questions-feeding-or-harassing-marine-mammals-wild",time:"7h ago",topic:"Animal Intelligence",region:"USA",title:"Marine Mammal Protection Act: Why It Is Illegal to Touch, Feed, Chase or Attempt to Interact With Wild Dolphins  -  and Why Researchers Think the Government Knows More Than It Says", summary:"The MMPA of 1972 makes it a federal crime to 'take' any marine mammal  -  defined as harass, hunt, capture, collect, or kill, including attempts. Penalties reach $100,000 per violation and one year imprisonment. Each dolphin in a pod = a separate violation. Verbal communication is not explicitly illegal  -  but any act that disrupts behavioral patterns qualifies as Level B harassment. The law applies to US citizens anywhere on Earth including international waters. Researchers note: you cannot legally interact with wild dolphins yet the Navy does so daily under congressional exemption. The 1986 MMPA amendment granted the Pentagon the right to take dolphins from the wild for 'national defense purposes'  -  a carve-out that exists in no other wildlife law.",upvotes:7800,comments:1201,credible:96,debunked:4,tags:["MMPA","Law","Dolphins","Pentagon","National Defense","Exemption"],premium:false},
  {id:"s64",slug:"global-dolphin-personhood-india-2013-malibu-2014-pacific-islands-2025-government",type:"research",source:"Give.do / The Print / Sonar",   sourceUrl:"https://wearesonar.org/dolphin-and-whale-nonhuman-personhood/",time:"8h ago",topic:"Animal Intelligence",region:"Global",title:"Global Dolphin Personhood: India 2013, Malibu 2014, Pacific Islands 2025  -  Governments Officially Declaring Dolphins Non-Human Persons", summary:"In 2013 India became the first nation to officially declare dolphins 'non-human persons'  -  banning all captive dolphin shows and stating it is 'morally unacceptable to keep them captive.' In 2014 Malibu's mayor passed a resolution granting dolphins and whales the right to freedom. In 2025 Pacific Island leaders granted cetaceans personhood status. The 2010 international Declaration of Rights for Cetaceans declared them persons with rights to life, freedom of movement, and not to be killed, captured, bred, or enslaved. The EU applied great ape research bans to cetaceans  -  calling them 'great apes of the water.'",upvotes:6900,comments:981,credible:90,debunked:10,tags:["Personhood","India","Dolphins","Rights","Non-Human","Global Law"],premium:false},
  {id:"s65",slug:"what-we-actually-know-about-dolphin-intelligence-cambridge-declaration-mirror-te",type:"research",source:"Wild Dolphin Project / Cambridge Declaration",sourceUrl:"https://www.wilddolphinproject.org",time:"9h ago",topic:"Animal Intelligence",region:"Global",title:"What We Actually Know About Dolphin Intelligence: Cambridge Declaration, Mirror Tests, Name Whistles, Culture, Grief  -  The Evidence Governments Don't Publicize", summary:"The 2012 Cambridge Declaration on Consciousness  -  signed in presence of Stephen Hawking  -  confirmed dolphins are conscious and self-aware. Dolphins pass the mirror self-recognition test (only humans, great apes, elephants, and magpies also pass). They choose unique name whistles before age one that are remembered 20+ years. Shark Bay Australia documents sponge tool use transmitted mother-to-daughter across three generations  -  qualifying as culture. Dr. Denise Herzing's 35-year Wild Dolphin Project documents syntax in communication, multigenerational dialect transmission, and grief  -  mothers carrying dead calves for weeks. A 2024 study confirmed dolphins imitate computer-generated sounds they have never heard.",upvotes:8400,comments:1302,credible:97,debunked:3,tags:["Consciousness","Cambridge","Mirror Test","Intelligence","Dolphins","Culture"],premium:false},
  {id:"s66",slug:"what-global-governments-may-be-hiding-about-dolphins-classified-programs-suppres",type:"research",source:"Dr. Denise Herzing / WDP",       sourceUrl:"https://www.wilddolphinproject.org/media/scientific-publications/",time:"10h ago",topic:"Animal Intelligence",region:"Global",title:"What Global Governments May Be Hiding About Dolphins: Classified Programs, Suppressed Intelligence Research, and the Question Nobody Asks", summary:"Several layers of classification surround dolphin research: (1) The CIA's 1964 Key West lab  -  full scope classified. (2) NMMP operational details  -  still classified 30+ years after the program was 'declassified.' (3) Soviet weaponization details  -  never fully disclosed. (4) Whether communication research with dolphins produced results beyond what was published  -  John Lilly's CIA-funded work never fully disclosed. (5) North Korea reportedly developing its own military dolphin program in 2024. (6) Whether the 1986 MMPA national defense exemption was used to take dolphins for intelligence  -  not just military  -  purposes. The most classified intelligence programs globally involve three things that overlap: consciousness, communication, and non-human intelligence. Dolphins are the intersection of all three.",upvotes:9800,comments:1601,credible:55,debunked:45,tags:["Classified","CIA","Dolphins","Consciousness","Hidden","Intelligence"],premium:true},
  {id:"s67",slug:"project-stargate-the-cia-20-million-25-year-psychic-espionage-program-now-fully-",type:"archive", source:"CIA Reading Room",              sourceUrl:"https://www.cia.gov/readingroom/collection/stargate",time:"1h ago",topic:"Remote Viewing & PSI",region:"USA",title:"Project STARGATE: The CIA's $20 Million 25-Year Psychic Espionage Program  -  Now Fully Declassified", summary:"Project STARGATE was the code name for a classified US Army / DIA program established 1978 at Fort Meade, Maryland to weaponize psychic phenomena for intelligence collection against the Soviet Union. Ran for over 20 years. $20 million budget confirmed. Physicists Hal Puthoff and Russell Targ at Stanford Research Institute were the lead scientists. CIA fully declassified 12 million pages of Stargate documents in 2017. The entire archive is searchable at the CIA Reading Room. Congressman Charles Rose stated in the House Intelligence Committee: 'It seemed like a hell of a cheap radar system  -  and if the Russians have it and we don't, we're in serious trouble.'",upvotes:11200,comments:1802,credible:95,debunked:5,tags:["Stargate","CIA","Remote Viewing","Declassified","DIA","Puthoff"],premium:false},
  {id:"s68",slug:"ingo-swann-the-psychic-who-remote-viewed-jupiter-before-pioneer-10-got-there-and",type:"research",source:"War History Online / Decrypted Matrix",sourceUrl:"https://www.warhistoryonline.com/war-articles/project-stargate.html",time:"2h ago",topic:"Remote Viewing & PSI",region:"USA",title:"Ingo Swann: The Psychic Who Remote-Viewed Jupiter Before Pioneer-10 Got There  -  and Found a Ring Nobody Knew Existed", summary:"Ingo Swann  -  artist and psychic, co-creator of remote viewing  -  was tested at Stanford Research Institute in 1972. CIA funded his research. In 1973 Swann remote-viewed Jupiter before the Pioneer-10 flyby and described a ring around the planet. Scientists assumed he had confused it with Saturn. When Pioneer-10 reached Jupiter the ring was confirmed. Swann also remote-viewed classified Soviet facilities from coordinates alone  -  with results that convinced CIA analysts to continue funding. He later claimed to have remote-viewed extraterrestrial bases on the Moon.",upvotes:9400,comments:1401,credible:71,debunked:29,tags:["Ingo Swann","Remote Viewing","Jupiter","CIA","Pioneer","Moon"],premium:false},
  {id:"s69",slug:"the-remote-viewers-who-described-soviet-nuclear-submarines-hidden-weapons-and-a-",type:"research",source:"Decrypted Matrix / Black Vault",  sourceUrl:"https://decryptedmatrix.com/project-stargate-cia-classified-psychic-espionage-program/",time:"3h ago",topic:"Remote Viewing & PSI",region:"USA",title:"The Remote Viewers Who Described Soviet Nuclear Submarines, Hidden Weapons, and a Secret Mars Colony from a Locked Room", summary:"Project Stargate remote viewers  -  including Pat Price (retired police commissioner), Joe McMoneagle (Army intelligence), and others  -  were given nothing but geographic coordinates and asked to describe what was there. Pat Price described a classified Soviet facility in Siberia with extraordinary accuracy in 1974. McMoneagle's readings of Soviet submarine construction were reportedly used in operational intelligence. A 1984 session described structures on Mars from 1 million years ago  -  the transcript remains in the CIA archive. The program was officially terminated in 1995, but researchers argue it went black rather than dark.",upvotes:10100,comments:1601,credible:64,debunked:36,tags:["Stargate","Remote Viewing","Soviet","Mars","Pat Price","McMoneagle"],premium:false},
  {id:"s70",slug:"cia-gateway-process-declassified-1983-army-report-concludes-human-consciousness-",type:"archive", source:"CIA Reading Room (direct PDF)",   sourceUrl:"https://www.cia.gov/readingroom/docs/CIA-RDP96-00788R001700210016-3.pdf",time:"4h ago",topic:"Remote Viewing & PSI",region:"USA",title:"CIA Gateway Process: Declassified 1983 Army Report Concludes Human Consciousness Can Leave the Body and Access Other Dimensions", summary:"A 1983 US Army Intelligence & Security Command analysis of the Monroe Institute's Gateway Experience  -  declassified and now freely downloadable from the CIA Reading Room  -  concludes that human consciousness can be separated from space-time and used to access information non-locally. The report uses physics, quantum mechanics, and holographic universe theory to explain how it works. The document was classified for 37 years. When released it went viral  -  millions read it. The Army concluded: it works, and the mechanism is rooted in physics not mysticism.",upvotes:14200,comments:2102,credible:88,debunked:12,tags:["CIA","Gateway Process","Consciousness","Monroe Institute","Declassified","OBE"],premium:false},
  {id:"s71",slug:"soviet-psychotronics-the-ussr-spent-60-million-rubles-annually-on-psychic-warfar",type:"research",source:"Black Vault / IRP.fas.org",       sourceUrl:"https://irp.fas.org/program/collect/stargate.htm",time:"5h ago",topic:"Remote Viewing & PSI",region:"USA",title:"Soviet Psychotronics: The USSR Spent 60 Million Rubles Annually on Psychic Warfare  -  Which Is Why the US Launched Stargate", summary:"The CIA launched the remote viewing program specifically because Soviet intelligence reports confirmed the USSR was spending the equivalent of $60 million annually on psychotronics  -  the weaponization of psychic phenomena. The CIA obtained a book by Canadian journalists Sheila Ostrander and Lynn Schroeder documenting Soviet PSI research and used it as justification to fund Puthoff and Targ. Both superpowers were simultaneously running classified psychic warfare programs throughout the Cold War. Neither has fully disclosed what they found.",upvotes:8800,comments:1301,credible:82,debunked:18,tags:["Soviet","Psychotronics","Cold War","CIA","Remote Viewing","USSR"],premium:false},
  {id:"s72",slug:"ancient-stargates-sumerian-gate-of-anu-egyptian-osiris-portal-tiahuanaco-gateway",type:"research",source:"Academic Block / Sacred Illusion",  sourceUrl:"https://www.academicblock.com/science/fringe-science/stargates-and-portals",time:"1h ago",topic:"Portals & Stargates",region:"Global",title:"Ancient Stargates: Sumerian Gate of Anu, Egyptian Osiris Portal, Tiahuanaco Gateway of the Sun  -  Ancient Civilizations Built Physical Portal Technology", summary:"Sumerian texts describe the Gate of Anu  -  a physical structure through which gods traversed dimensions. The Egyptian Book of the Dead describes 21 gates with guardians that souls must navigate. Tiahuanaco's Gateway of the Sun in Bolivia is aligned to precise astronomical coordinates and features carvings researchers argue depict portal activation sequences. Researcher and archaeologist Dr. Heather Lynn connects these to Anunnaki technology described in Sitchin's translations. Mike Ricksecker's Portals to the Stars documents physical portal research across ancient global sites.",upvotes:7800,comments:1102,credible:48,debunked:52,tags:["Stargate","Sumerian","Egypt","Tiahuanaco","Portal","Ancient"],premium:false},
  {id:"s73",slug:"the-montauk-project-classified-time-travel-mind-control-and-interdimensional-por",type:"research",source:"Sacred Illusion / MagellanTV",     sourceUrl:"https://www.sacredillusion.com/stargates-and-doors-to-nowhere-portals-illusions-or-entrances-to-elsewhere/",time:"2h ago",topic:"Portals & Stargates",region:"USA",title:"The Montauk Project: Classified Time Travel, Mind Control, and Interdimensional Portals at Camp Hero Air Force Station 1943-1983", summary:"The Montauk Project  -  documented in books by Preston Nichols and Peter Moon  -  alleges that Camp Hero, Montauk NY, was the site of classified government experiments in time travel, mind control, and opening interdimensional portals from the 1940s through the 1980s. The theory connects to the 1943 Philadelphia Experiment in which the USS Eldridge reportedly vanished from a Philadelphia shipyard. A psychic named Duncan Cameron reportedly opened a time portal that created a tear in space-time that researchers claim was deliberately collapsed. The site is now Camp Hero State Park. The underground facilities remain sealed.",upvotes:8200,comments:1201,credible:38,debunked:62,tags:["Montauk","Time Travel","Portal","Camp Hero","Philadelphia Experiment","Classified"],premium:false},
  {id:"s74",slug:"cern-large-hadron-collider-scientists-searching-for-extra-dimensions-and-dark-ma",type:"research",source:"CERN / Israel First Substack",    sourceUrl:"https://home.cern/science/experiments/lhc",time:"3h ago",topic:"Portals & Stargates",region:"Global",title:"CERN Large Hadron Collider: Scientists Searching for 'Extra Dimensions' and Dark Matter  -  Critics Say It Already Opened Something", summary:"CERN has publicly stated that one of the goals of the Large Hadron Collider is to find evidence of extra dimensions and dark matter. In 2024 CERN activated the LHC during the solar eclipse and stated: 'What exactly we would detect would depend on the number of extra dimensions.' Critics argue this is portal research under a physics label. The LHC sits on the ancient site of St. Genis-Pouilly  -  a Roman town whose name derives from the Latin Appolliacum, built over a temple to Apollo described as a gateway to the underworld. CERN's campus features a statue of Shiva performing the Nataraja  -  the cosmic dance of creation and destruction.",upvotes:9100,comments:1502,credible:45,debunked:55,tags:["CERN","LHC","Extra Dimensions","Portal","Dark Matter","Shiva"],premium:false},
  {id:"s75",slug:"skinwalker-ranch-instrumented-scientific-research-confirms-anomalous-portal-like",type:"research",source:"Skinwalker Ranch / George Knapp",  sourceUrl:"https://skinwalker-ranch.com",time:"4h ago",topic:"Portals & Stargates",region:"USA",title:"Skinwalker Ranch: Instrumented Scientific Research Confirms Anomalous Portal-Like Phenomena  -  DoD Funded Investigation", summary:"Skinwalker Ranch in Utah has been the subject of instrumented scientific investigation funded by the Department of Defense through the Advanced Aerospace Weapon System Applications Program (AAWSAP)  -  the same program that spawned the AATIP UAP investigation. Researchers document: UAP appearing and disappearing in specific sky locations consistently, cattle mutilation with surgical precision, poltergeist phenomena, and what instruments record as localized tears in space measuring magnetic, electromagnetic, and radiation anomalies simultaneously. Former DIA official Dr. James Lacatski led the DoD investigation. His findings remain classified.",upvotes:10400,comments:1601,credible:61,debunked:39,tags:["Skinwalker","Portal","DoD","AAWSAP","DIA","Classified","UAP"],premium:false},
  {id:"s76",slug:"the-iraqi-stargate-why-the-us-established-military-zones-around-ancient-sumerian",type:"research",source:"Iraq Stargate / Medium",          sourceUrl:"https://medium.com/@iram.ahmed1997/the-iraqi-stargate-conspiracy-a-modern-perspective-on-an-ancient-mystery-18d3cd39ff8f",time:"5h ago",topic:"Portals & Stargates",region:"Iraq Iraq",title:"The Iraqi Stargate: Why the US Established Military Zones Around Ancient Sumerian Sites Immediately After Invasion in 2003", summary:"Researchers document that following the 2003 Iraq invasion, US forces established restricted military zones around ancient Sumerian sites including Ur, Nineveh, and Babylon  -  while the Baghdad Museum was looted of thousands of irreplaceable artifacts with no military intervention. Some claim soldiers reported time anomalies and electromagnetic disturbances near ancient sites. The theory: Sumerian tablets describe the Gate of Anu as a physical device, and the real objective of occupying Iraq was to control access to ancient portal technology buried beneath the oldest human civilization on Earth.",upvotes:8600,comments:1302,credible:35,debunked:65,tags:["Iraq","Stargate","Sumerian","2003","Artifacts","Gate of Anu"],premium:true},
  {id:"s77",slug:"global-portal-sites-mount-shasta-sedona-stonehenge-machu-picchu-easter-island-wh",type:"research",source:"Thirdi.us / Tourism and Travel",   sourceUrl:"https://thirdi.us/blog/2024/07/unlocking-the-mysteries-of-stargates-portals-to-other-dimensions-and-realms/",time:"6h ago",topic:"Portals & Stargates",region:"Global",title:"Global Portal Sites: Mount Shasta, Sedona, Stonehenge, Machu Picchu, Easter Island  -  What Instruments Detect at Each Location", summary:"Researchers have documented measurable electromagnetic anomalies at every major ancient site associated with portal or vortex activity. Mount Shasta: Native American traditions of underground cities and interdimensional beings, plus measured magnetic anomalies. Sedona: Benjamin Lonetree's decade of magnetometer data. Stonehenge: confirmed solar and lunar alignment precision beyond architectural necessity. Machu Picchu: built on geological intersection of multiple fault lines creating piezoelectric energy. Easter Island: moai aligned to specific star systems. The common thread: all are built on granite and quartz formations that generate electromagnetic fields under tectonic pressure.",upvotes:7400,comments:1101,credible:55,debunked:45,tags:["Portals","Mount Shasta","Stonehenge","Sedona","Electromagnetic","Ancient Sites"],premium:false},
  {id:"s78",slug:"missing-411-david-paulides-documents-9000-hours-of-research-into-unexplained-nat",type:"research",source:"CanAm Missing / Missing411.com",  sourceUrl:"https://www.canammissing.com",time:"1h ago",topic:"Unresolved Events",region:"USA",title:"Missing 411: David Paulides Documents 9,000+ Hours of Research Into Unexplained National Park Disappearances  -  Patterns That Defy Explanation", summary:"Former law enforcement officer David Paulides spent 9,000+ hours investigating disappearances in US National Parks after a ranger tipped him off to a disturbing pattern. His findings: victims disappear in good weather with no distress call. Bodies are found miles away in terrain search teams already covered. Clothing is missing or neatly arranged. No trail of passage. Berry bushes stripped near discovery sites. Victims are often found in or near water. The National Park Service refused his FOIA request for a list of missing persons  -  citing cost. No other government database tracks this.",upvotes:14200,comments:2102,credible:72,debunked:28,tags:["Missing 411","Paulides","National Parks","Disappearances","FOIA","Unexplained"],premium:false},
  {id:"s79",slug:"the-missing-411-profile-points-30-consistent-patterns-across-hundreds-of-disappe",type:"research",source:"Missing411.com / CanAm",          sourceUrl:"https://missing411.com",time:"2h ago",topic:"Unresolved Events",region:"USA",title:"The Missing 411 Profile Points: 30+ Consistent Patterns Across Hundreds of Disappearances That Cannot Be Explained by Conventional Search Theory", summary:"Paulides identified 30+ profile points appearing consistently across cases: disappearances near boulder fields or granite outcroppings; victims last seen near berry patches; dogs cannot track scent; victims found in water despite not being near water when last seen; clothing found neatly folded or missing entirely; victims recovered with no memory of what happened; weather changes immediately after disappearance; discovery sites already searched multiple times. The clusters map to specific geographic zones. The NPS has never commented. Some researchers point to interdimensional portals. Others point to predatory human networks. The cases remain officially unexplained.",upvotes:12800,comments:1901,credible:65,debunked:35,tags:["Missing 411","Profile Points","National Parks","Paulides","Patterns"],premium:false},
  {id:"s80",slug:"missing-411-the-hunted-experienced-hunters-with-military-training-vanish-in-the-",type:"research",source:"CanAm Missing Project",            sourceUrl:"https://www.canammissing.com",time:"3h ago",topic:"Unresolved Events",region:"USA",title:"Missing 411: The Hunted  -  Experienced Hunters With Military Training Vanish in the Woods. Something Is Hunting Them Back", summary:"Paulides' 2019 documentary The Hunted focuses exclusively on experienced hunters  -  many with military backgrounds  -  who vanished in wilderness areas. These are not lost hikers. These are men with compass skills, survival training, and firearms who were in familiar territory. Several cases: hunters who called family to say they were coming home and never arrived. Shots fired with no casualty found. Weapons found but hunter gone. Paulides argues the pattern in hunter disappearances is distinct from civilian cases and suggests an active predatory intelligence.",upvotes:11400,comments:1701,credible:61,debunked:39,tags:["Missing 411","Hunters","Military","Paulides","Predator","Wilderness"],premium:false},
  {id:"s81",slug:"geometric-unity-eric-weinstein-suppressed-unified-field-theory-harvard-mathemati",type:"research",source:"GeometricUnity.org",               sourceUrl:"https://geometricunity.org/",                time:"1h ago", topic:"Forbidden Science",        region:"USA",  title:"Geometric Unity: Eric Weinstein's Suppressed Unified Field Theory  -  Harvard Mathematician vs. The Physics Establishment", summary:"Eric Weinstein  -  Harvard PhD mathematician, former managing director of Thiel Capital  -  has spent decades developing Geometric Unity: an attempt to unify general relativity and the Standard Model by recovering the seemingly incompatible geometries of fundamental physics from a single minimal structure. Presented at Oxford in 2013, the theory was praised by Marcus du Sautoy but met institutional resistance because Weinstein refused to publish before the community was ready to evaluate it fairly. He argues the physics establishment uses gatekeeping and peer review as tools of suppression rather than validation.", upvotes:8200, comments:1201, credible:62, debunked:38, tags:["Geometric Unity","Weinstein","Physics","Suppressed","Unified Theory"], premium:false},
  {id:"s82",slug:"the-2013-oxford-lecture-eric-weinstein-geometric-unity-presented-to-the-academy-",type:"archive",  source:"Oxford Mathematical Institute",    sourceUrl:"https://geometricunity.org/2013-oxford-lecture/",   time:"2h ago", topic:"Forbidden Science",        region:"UK",   title:"The 2013 Oxford Lecture: Eric Weinstein's Geometric Unity Presented to the Academy  -  Full Transcript Available", summary:"On May 23, 2013, Eric Weinstein presented Geometric Unity at Oxford's Martin Wood Lecture, introduced by Marcus du Sautoy who called it a potential unified theory of physics. The full video was released April 1, 2020 as a special episode of The Portal podcast. The full transcript is archived at GeometricUnity.org. Physicists David Kaplan and Jim al-Khalili expressed skepticism, largely because no equations were published alongside the talk. Weinstein has since self-published a working draft paper. The Oxford Mathematical Institute listing for the talk remains accessible.", upvotes:6400, comments:881,  credible:58, debunked:42, tags:["Oxford","Geometric Unity","Weinstein","2013","Unified Theory"], premium:false},
  {id:"s83",slug:"eric-weinstein-scientific-gatekeeping-institutional-corruption-and-why-the-physi",type:"research",source:"The Portal Group / theportal.group", sourceUrl:"https://theportal.group/",                    time:"3h ago", topic:"Forbidden Science",        region:"USA",  title:"Eric Weinstein: Scientific Gatekeeping, Institutional Corruption, and Why the Physics Establishment Suppresses Outsider Theories", summary:"Through The Portal podcast, Eric Weinstein has documented in detail how academic institutions  -  particularly physics departments  -  use funding structures, peer review capture, and credentialing requirements to systematically exclude theories from outside the approved framework. Weinstein coined the term 'Intellectual Dark Web' to describe thinkers willing to discuss ideas that institutions have declared off-limits. He argues string theory's dominance despite zero experimental verification is the defining example of how physics became a gatekept ideology rather than a science.", upvotes:9100, comments:1302, credible:71, debunked:29, tags:["Weinstein","Gatekeeping","String Theory","IDW","Institutional Corruption"], premium:false},
  {id:"s84",slug:"eric-weinstein-government-secretly-recruited-him-to-help-mediate-uap-disclosure-",type:"research",source:"IBTimes / JRE #2503",               sourceUrl:"https://www.ibtimes.co.uk/eric-weinstein-government-ufo-disclosure-1798302", time:"4h ago", topic:"UAP & Anomalous",          region:"USA",  title:"Eric Weinstein: Government Secretly Recruited Him to Help Mediate UAP Disclosure  -  Credible Sources, White Sands 'Infestation', Epstein as Intelligence Operation", summary:"In 2026 Weinstein publicly stated that credible government-connected figures secretly reached out to recruit him as a disclosure mediator  -  briefing influential public figures to gradually explain UAP realities to the public. On Joe Rogan Experience #2503 (May 2026), Weinstein described multiple credible accounts of 'infestation problems' at White Sands  -  objects appearing that may be American, foreign, or genuinely unknown. He also argues the Epstein network was primarily an intelligence operation targeting America's scientific and intellectual assets  -  the sexual element was cover.", upvotes:14200, comments:2201, credible:65, debunked:35, tags:["Weinstein","UAP","Disclosure","Epstein","White Sands","Rogan"], premium:false},
  {id:"s85",slug:"geometric-unity-working-draft-the-self-published-paper-and-the-theory-that-chall",type:"research",source:"The Portal Wiki / GeometricUnity.org",sourceUrl:"https://theportal.wiki/wiki/Theory_of_Geometric_Unity", time:"5h ago", topic:"Forbidden Science",        region:"USA",  title:"Geometric Unity Working Draft: The Self-Published Paper and the Theory That Challenges String Theory's Monopoly on Physics Funding", summary:"In April 2021 Weinstein self-published a working draft of Geometric Unity, labeling it 'a work of entertainment'  -  a deliberate legal and institutional shield. The paper proposes that the source code of the universe is overwhelmingly likely to be a purely geometric operating system. It challenges string theory not just scientifically but politically: Weinstein documents how string theory has consumed physics funding for 40 years while making zero testable predictions, crowding out any competing framework including his own.", upvotes:7800, comments:1041, credible:55, debunked:45, tags:["Geometric Unity","String Theory","Working Draft","Weinstein","Physics"], premium:true},
  {id:"s86",slug:"maj-gen-neil-mccasland-disappears-feb-27-2026-air-force-research-lab-commander-w",type:"news",    source:"NewsNation / CNN / Fox News",       sourceUrl:"https://www.newsnationnow.com/missing/mccasland-disappearance-national-security-concern-ufo-uap/", time:"1h ago", topic:"Unresolved Events",       region:"USA",  title:"Maj. Gen. Neil McCasland Disappears Feb. 27, 2026 - Air Force Research Lab Commander, Wright-Patterson, Tom DeLonge Consultant, UFO Secrets Holder", summary:"Retired Air Force Major General William Neil McCasland - former commander of the Air Force Research Laboratory at Wright-Patterson, former Director of Special Programs for the Under Secretary of Defense, and a consultant to Tom DeLonge's To The Stars Academy - disappeared from his Albuquerque NM home on foot on February 27, 2026, days after Trump ordered Pentagon UAP disclosure. He left his phone, glasses, and wearable devices at home. His wallet, a .38 revolver, and hiking boots are missing. The FBI joined the search. Ross Coulthart called it a grave national security crisis - McCasland held some of the most sensitive UAP secrets in US government history.", upvotes:18200, comments:2901, credible:90, debunked:10, tags:["McCasland","Air Force","UAP","Missing","Wright-Patterson","Disclosure"], premium:false},
  {id:"s87",slug:"the-bermuda-triangle-what-noaa-actually-says-magnetic-anomalies-methane-hydrates",type:"research",source:"NOAA Ocean Explorer",               sourceUrl:"https://oceanexplorer.noaa.gov",         time:"2h ago", topic:"Ocean & Earth",           region:"Global",title:"The Bermuda Triangle: What NOAA Actually Says - Magnetic Anomalies, Methane Hydrates, and the Official Non-Explanation", summary:"NOAA's official position is that the Bermuda Triangle does not exist as a defined region and that disappearances there are no more frequent than in other heavily traveled oceanic areas. Yet researchers document consistent magnetic compass anomalies, massive methane hydrate deposits capable of sinking ships by reducing water density, and a geological rift zone unlike anywhere else in the Atlantic. The US Navy does not officially recognize the Bermuda Triangle but maintains detailed classified charts of the region.", upvotes:6800, comments:1021, credible:61, debunked:39, tags:["Bermuda Triangle","NOAA","Magnetic","Methane","Ocean"], premium:false},
  {id:"s88",slug:"atlantis-plato-original-account-sonar-anomalies-near-the-azores-and-the-richat-s",type:"research",source:"Atlantipedia / Plato Primary Source",sourceUrl:"https://atlantipedia.ie",                time:"3h ago", topic:"Ocean & Earth",           region:"Global",title:"Atlantis: Plato's Original Account, Sonar Anomalies Near the Azores, and the Richat Structure - What Researchers Are Actually Finding", summary:"Plato's Timaeus and Critias describe Atlantis as a technologically advanced naval civilization destroyed in a single day and night around 9,600 BCE by earthquakes and floods. Modern researchers have identified three candidate locations with geological evidence: the Azores plateau (seamount structures that were above water 12,000 years ago), the Richat Structure in Mauritania (a 50km circular formation matching Plato's concentric ring description), and the Caribbean basin. Sonar mapping of the Azores has revealed what some researchers describe as rectilinear structures at depth.", upvotes:7200, comments:1102, credible:52, debunked:48, tags:["Atlantis","Plato","Azores","Richat","Ocean"], premium:false},
  {id:"s89",slug:"95-percent-of-earth-oceans-remain-unexplored-what-has-been-found-includes-struct",type:"research",source:"Oceanography / Marine Geology Journal",sourceUrl:"https://oceanexplorer.noaa.gov",       time:"4h ago", topic:"Ocean & Earth",           region:"Global",title:"95% of Earth's Oceans Remain Unexplored - What Has Been Found in the Deep Includes Structures, Sounds, and Signals Science Cannot Explain", summary:"NOAA estimates 95% of Earth's oceans remain unexplored. The Bloop sound recorded in 1997 was louder than any known biological source. The Julia sound in 1999, the Train in 1994, and the Upsweep in 1991 all remain officially unexplained. In 2012 Google Ocean users identified a grid-like structure on the ocean floor off the coast of Africa spanning 2,200 square miles with lines spaced at perfect intervals. NOAA attributed it to sonar data artifacts. Independent researchers disagree.", upvotes:5900, comments:881, credible:68, debunked:32, tags:["Ocean","Unexplored","Bloop","Deep Sea","Anomalies"], premium:false},
  {id:"s90",slug:"the-hutchison-effect-tesla-earthquake-machine-and-evidence-that-directed-energy-",type:"podcast", source:"Mysterious Universe Podcast",       sourceUrl:"https://mysteriousuniverse.org",         time:"5h ago", topic:"Ocean & Earth",           region:"Global",title:"The Hutchison Effect, Tesla's Earthquake Machine, and Evidence That Directed Energy Can Manipulate Earth's Geological Systems", summary:"John Hutchison's experiments documented by Canadian military researchers showed that high-frequency electromagnetic fields can cause levitation, metal fusion, and strange material anomalies. Nikola Tesla claimed his mechanical oscillator created resonance vibrations that began shaking the neighborhood around his New York lab in 1898 - and that a larger version could split the Earth in two. Researchers connecting HAARP, directed energy weapons, and unusual earthquake patterns argue governments have had the ability to manipulate geological systems for decades.", upvotes:4800, comments:721, credible:41, debunked:59, tags:["Hutchison","Tesla","HAARP","Earthquake","Earth Energy"], premium:false},
];

// --- SEED COMMUNITY POSTS -----------------------------------------------------
export const SEED_POSTS = [
  { id:"c1", user:"RedactedArchive",    badge:"Investigator", time:"2h ago",  topic:"Government & Intelligence",    region:"USA",title:"Cross-referencing Epstein flight logs  -  34 names never reported on",                             body:"Using court-filed documents and FOIA releases I've cross-referenced 34 names on the manifests that have never appeared in any mainstream coverage. Several are still in active government positions.", upvotes:4211, comments:891, refs:[{label:"DocumentCloud Court Files",url:"https://www.documentcloud.org"}], tags:["Epstein","FOIA"], confidence:"likely", contentType:"research", pinned:true },
  { id:"c2", user:"EnochResearcher",    badge:"Researcher",   time:"3h ago",  topic:"Biblical & Religious Records",  region:"Middle East",title:"Parallel passages between Book of Enoch and Genesis 6  -  line by line comparison",               body:"The Book of Enoch was found among the Dead Sea Scrolls, confirming it predates the New Testament. I've done a full side-by-side of Enoch chapters 6-11 and Genesis 6:1-4. The Nephilim account is nearly identical  -  suggesting a common source text.",         upvotes:3102, comments:567, refs:[{label:"Dead Sea Scrolls Digital Library",url:"https://www.deadseascrolls.org.il"},{label:"Book of Enoch Full Text",url:"https://www.amazon.com/Book-Enoch-R-H-Charles/dp/1478318759"}], tags:["Enoch","Nephilim","Genesis"], confidence:"confirmed", contentType:"research", pinned:true },
  { id:"c3", user:"OceanDepthsOnly",    badge:"Researcher",   time:"4h ago",  topic:"Animal Intelligence",           region:"Global",title:"Dolphins in Shark Bay Passing Tool Use to Offspring  -  Documented Across 3 Generations",          body:"Research from Shark Bay, Australia documents bottlenose dolphins using marine sponges to protect their snouts while foraging. This behavior is taught exclusively mother to daughter and has been documented across three generations  -  qualifying as culture.",    upvotes:3918, comments:621, refs:[{label:"NOAA Ocean Exploration",url:"https://oceanexplorer.noaa.gov"},{label:"Shark Bay Research",url:"https://www.monkeymia.com.au"}], tags:["Dolphins","Tool Use","Culture"], confidence:"confirmed", contentType:"research", pinned:false },
  { id:"c4", user:"HistoricalRecord77", badge:"Analyst",      time:"8h ago",  topic:"Giants & Nephilim",            region:"USA",title:"1880s News Archives: Giant Skeleton Reports Before Smithsonian Consolidated the Finds",          body:"I've compiled 47 newspaper articles from 1848-1912 reporting giant skeletal discoveries across Ohio, Illinois, and Tennessee. All were transferred to the Smithsonian. None are publicly accessible today. The timing correlates with the institution's founding.", upvotes:5200, comments:890, refs:[{label:"NewspaperArchive.com",url:"https://newspaperarchive.com"},{label:"Smithsonian FOIA Records",url:"https://www.si.edu/foia"}], tags:["Giants","Smithsonian","Archives"], confidence:"likely", contentType:"research", pinned:false },
];

// --- MEDIA_LIBRARY, SOURCES, PRIVACY_POLICY -----------------------------------
// IMPORTANT: These sections are UNCHANGED from your original data.js
// Copy everything from "// --- MEDIA LIBRARY ----" to the end of your 
// original data.js and paste it here, replacing this comment.
// Only SEED_STORIES needed updating (the slug: fields added above).
